### PR TITLE
Feature aqara p1 motion sensor

### PR DESCRIPTION
**Pull request by skymania**

### CODE REVIEW

**Comment by andreasvikke** [comment]
Have had no issues running this PR, with 2 motion sensors for around a week now👍 
All changes to settings are also taking affect without issues

**Comment by TedTolboom** [comment]
Thanks for the PR.
Looking to your code, basic operation should work.

I don't understand why you defined the settings also as capabilities, doesn't sound logical to me? 
To make them available as flowcards?

**Comment by TedTolboom** [comment]
I'll merge it to a separate branch and work from there.

**Comment by TedTolboom** [comment]
Released to the app store. Thanks for the contribution!
Do note that due to the changes I made, updating to v1.6.0 will mean you need to re-include your device.

**Pull request merged**
