### PR TITLE
lumi.remote.b286acn02

### PR DESCRIPTION
**Pull request by guestus**
lumi.remote.b286acn02

### CODE REVIEW

**Comment by TedTolboom** [comment]
Can you be more specific to motivate the change?

Has it been tested to work with all options (scenes)?

**Comment by guestus** [comment]
Hi, im sorry.
b286acn02 (D1 switch) use same clusters genOnOff and genMultistateInput as a b286acn01.
All scenes works correctly - left, right, both with single, double and held. 
But today i need check for onXiaomiLifelineAttributeReport for battery status. will check on.

**Comment by TedTolboom** [comment]
Ah, hold on, is this the Two button version of the D1 switch??

**Comment by guestus** [comment]
yes, this is Aqara Wall Wireless Switch Double Key D1 (WXKG07LM)

**Comment by TedTolboom** [comment]
I'd add them as separate drivers... otherwise people will look and miss
support for the Aqara D1 series.
They're here on my desk, but I'm waiting for first feedback on the test
version before adding them.

**Comment by guestus** [comment]
Ok, thanks.

**Pull request closed without merging**
